package modig;

import java.util.ArrayList;

/*





Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 
 
 i++
 
 
 */

public class Uppgift2 {
	
	public static void main(String[] args)
	{
		int fib1 = 1, fib2 = 1, fib3 = 0;
		ArrayList<Integer> even = new ArrayList();
		System.out.println(even.size());
		even.add(1);
		System.out.println(even.add(1));
		System.out.println(even.size());
		even.add(2);
		System.out.println(even.size());
		
		
		int sum = 0;
		//System.out.println(4%2);
		
		for(int i = 0; i < 32; i++)
		{
			if(fib2 % 2 == 0)
			{
				sum += fib2;
				//System.out.println(fib2);
			}
			//System.out.println(fib2);
			fib3 = (fib1 + fib2);
			fib1 = fib2;
			fib2 = fib3;
			
			
			
					
		
		}
		//System.out.println(sum);
		
		
	
		
		
		
	}

}
